# What is your search engine?

# engine = "https://duckduckgo.com/?q="
#engine = "https://baidu.com/s?wd="
#engine = "https://bing.com/search?q="
engine = "https://google.com/search?q="
#engine = "https://search.yahoo.com/search?p="
#engine = "https://yandex.ru/search/?text="
