#!/usr/bin/env sh

# Where is the DIR for dotfiles?
DOTFILES="${HOME}/.files"
TPM="${HOME}/.tmux/plugins/tpm"

# Clone dotfiles if we don't have it cloned yet
# Or update if we have it
[ -d $DOTFILES ] || git clone https://github.com/mxaddict/dotfiles.git $DOTFILES
cd $DOTFILES && git checkout main && git pull

# Clone tpm if we don't have it cloned yet
# Or update if we have it
[ -d $TPM ] || git clone https://github.com/tmux-plugins/tpm $TPM
cd $TPM && git pull && cd $DOTFILES

# Create our base dir structure
for dir in .config/fish .config/nvim/lua/plugins .config/kitty .config/tmux
do
    echo "Creating $HOME/$dir..."
    mkdir -p $HOME/$dir
done

# Copy dotfiles
for file in .gitconfig .gitignore .config/fish/config.fish .config/starship.toml .config/tmux/tmux.conf
do
    echo "Copying $file"
    cp $file $HOME/$file
done

# Copy kitty
for file in .config/kitty/kitty.conf .config/kitty/theme.conf
do
    echo "Copying $file"
    cp $file $HOME/$file
done

# Copy nvim configs
for file in .config/nvim/init.lua .config/nvim/lua/main.lua .config/nvim/lua/remap.lua
do
    echo "Copying $file"
    cp $file $HOME/$file
done

echo "Deleting old .config/nvim/lua/plugins/..."
rm -rf $HOME/.config/nvim/lua/plugins

echo "Copying new .config/nvim/lua/plugins/..."
cp -r .config/nvim/lua/plugins $HOME/.config/nvim/lua/plugins
